// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ResxParser.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QuizLearningResources_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuizLearningResources_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ResxParser.Resources.QuizLearningResources.en", typeof(QuizLearningResources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string acess_code_is_required {
            get {
                return ResourceManager.GetString("acess_code_is_required", resourceCulture);
            }
        }
        
        internal static string added_group_with_success {
            get {
                return ResourceManager.GetString("added_group_with_success", resourceCulture);
            }
        }
        
        internal static string alert {
            get {
                return ResourceManager.GetString("alert", resourceCulture);
            }
        }
        
        internal static string alert_before_downlaod_quiz {
            get {
                return ResourceManager.GetString("alert_before_downlaod_quiz", resourceCulture);
            }
        }
        
        internal static string cant_download_quiz {
            get {
                return ResourceManager.GetString("cant_download_quiz", resourceCulture);
            }
        }
        
        internal static string cant_save_quiz {
            get {
                return ResourceManager.GetString("cant_save_quiz", resourceCulture);
            }
        }
        
        internal static string downloading_quiz_content {
            get {
                return ResourceManager.GetString("downloading_quiz_content", resourceCulture);
            }
        }
        
        internal static string email_required {
            get {
                return ResourceManager.GetString("email_required", resourceCulture);
            }
        }
        
        internal static string fill_acces_code {
            get {
                return ResourceManager.GetString("fill_acces_code", resourceCulture);
            }
        }
        
        internal static string fill_email {
            get {
                return ResourceManager.GetString("fill_email", resourceCulture);
            }
        }
        
        internal static string fill_name {
            get {
                return ResourceManager.GetString("fill_name", resourceCulture);
            }
        }
        
        internal static string fill_password {
            get {
                return ResourceManager.GetString("fill_password", resourceCulture);
            }
        }
        
        internal static string fill_position {
            get {
                return ResourceManager.GetString("fill_position", resourceCulture);
            }
        }
        
        internal static string fill_surname {
            get {
                return ResourceManager.GetString("fill_surname", resourceCulture);
            }
        }
        
        internal static string have_been_challenged {
            get {
                return ResourceManager.GetString("have_been_challenged", resourceCulture);
            }
        }
        
        internal static string http_timeout_exceded {
            get {
                return ResourceManager.GetString("http_timeout_exceded", resourceCulture);
            }
        }
        
        internal static string impossible_upload_quiz {
            get {
                return ResourceManager.GetString("impossible_upload_quiz", resourceCulture);
            }
        }
        
        internal static string invalid_email {
            get {
                return ResourceManager.GetString("invalid_email", resourceCulture);
            }
        }
        
        internal static string invalid_password {
            get {
                return ResourceManager.GetString("invalid_password", resourceCulture);
            }
        }
        
        internal static string invalid_surname {
            get {
                return ResourceManager.GetString("invalid_surname", resourceCulture);
            }
        }
        
        internal static string invalid_username {
            get {
                return ResourceManager.GetString("invalid_username", resourceCulture);
            }
        }
        
        internal static string last_updated_when {
            get {
                return ResourceManager.GetString("last_updated_when", resourceCulture);
            }
        }
        
        internal static string loading_quiz {
            get {
                return ResourceManager.GetString("loading_quiz", resourceCulture);
            }
        }
        
        internal static string message_box_cancel {
            get {
                return ResourceManager.GetString("message_box_cancel", resourceCulture);
            }
        }
        
        internal static string message_box_no {
            get {
                return ResourceManager.GetString("message_box_no", resourceCulture);
            }
        }
        
        internal static string message_box_ok {
            get {
                return ResourceManager.GetString("message_box_ok", resourceCulture);
            }
        }
        
        internal static string message_box_yes {
            get {
                return ResourceManager.GetString("message_box_yes", resourceCulture);
            }
        }
        
        internal static string no_connection_try_later {
            get {
                return ResourceManager.GetString("no_connection_try_later", resourceCulture);
            }
        }
        
        internal static string no_internet_will_sync_result_later {
            get {
                return ResourceManager.GetString("no_internet_will_sync_result_later", resourceCulture);
            }
        }
        
        internal static string password_recovered {
            get {
                return ResourceManager.GetString("password_recovered", resourceCulture);
            }
        }
        
        internal static string personality_test_content {
            get {
                return ResourceManager.GetString("personality_test_content", resourceCulture);
            }
        }
        
        internal static string profile_updated_with_sucess {
            get {
                return ResourceManager.GetString("profile_updated_with_sucess", resourceCulture);
            }
        }
        
        internal static string regist_success {
            get {
                return ResourceManager.GetString("regist_success", resourceCulture);
            }
        }
        
        internal static string saving_quiz_content {
            get {
                return ResourceManager.GetString("saving_quiz_content", resourceCulture);
            }
        }
        
        internal static string storage_permission {
            get {
                return ResourceManager.GetString("storage_permission", resourceCulture);
            }
        }
        
        internal static string unexpeted_error {
            get {
                return ResourceManager.GetString("unexpeted_error", resourceCulture);
            }
        }
        
        internal static string want_to_delete {
            get {
                return ResourceManager.GetString("want_to_delete", resourceCulture);
            }
        }
        
        internal static string want_to_exit {
            get {
                return ResourceManager.GetString("want_to_exit", resourceCulture);
            }
        }
        
        internal static string wrong_password_or_email {
            get {
                return ResourceManager.GetString("wrong_password_or_email", resourceCulture);
            }
        }
        
        internal static string challenge_canceled {
            get {
                return ResourceManager.GetString("challenge_canceled", resourceCulture);
            }
        }
        
        internal static string challenge_timeout {
            get {
                return ResourceManager.GetString("challenge_timeout", resourceCulture);
            }
        }
        
        internal static string new_challenge {
            get {
                return ResourceManager.GetString("new_challenge", resourceCulture);
            }
        }
        
        internal static string oponent_denied {
            get {
                return ResourceManager.GetString("oponent_denied", resourceCulture);
            }
        }
        
        internal static string oponent_unavailable {
            get {
                return ResourceManager.GetString("oponent_unavailable", resourceCulture);
            }
        }
        
        internal static string wanna_play {
            get {
                return ResourceManager.GetString("wanna_play", resourceCulture);
            }
        }
        
        internal static string release_info {
            get {
                return ResourceManager.GetString("release_info", resourceCulture);
            }
        }
    }
}
