// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ResxConverter {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResx1 {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResx1() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ResxConverter.SharedResx1", typeof(SharedResx1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string FeedbackTitleDone {
            get {
                return ResourceManager.GetString("FeedbackTitleDone", resourceCulture);
            }
        }
        
        internal static string FeedbackTitleAlreadyDone {
            get {
                return ResourceManager.GetString("FeedbackTitleAlreadyDone", resourceCulture);
            }
        }
        
        internal static string FeedbackTitleItsSimple {
            get {
                return ResourceManager.GetString("FeedbackTitleItsSimple", resourceCulture);
            }
        }
        
        internal static string FeedbackButtonOk {
            get {
                return ResourceManager.GetString("FeedbackButtonOk", resourceCulture);
            }
        }
        
        internal static string FeedbackSubscribeInsuranceDescription {
            get {
                return ResourceManager.GetString("FeedbackSubscribeInsuranceDescription", resourceCulture);
            }
        }
        
        internal static string FeedbackActivateJumboVisaCardDescription {
            get {
                return ResourceManager.GetString("FeedbackActivateJumboVisaCardDescription", resourceCulture);
            }
        }
        
        internal static string FeedbackSubscribeDigitalExtractDescription {
            get {
                return ResourceManager.GetString("FeedbackSubscribeDigitalExtractDescription", resourceCulture);
            }
        }
        
        internal static string FeedbackExtractDuplicateDescription {
            get {
                return ResourceManager.GetString("FeedbackExtractDuplicateDescription", resourceCulture);
            }
        }
        
        internal static string FeedbackChangePaymentMethodDescription {
            get {
                return ResourceManager.GetString("FeedbackChangePaymentMethodDescription", resourceCulture);
            }
        }
        
        internal static string FeedbackReplaceCardDescription {
            get {
                return ResourceManager.GetString("FeedbackReplaceCardDescription", resourceCulture);
            }
        }
        
        internal static string FeedbackMovementsSendByEmailDescription {
            get {
                return ResourceManager.GetString("FeedbackMovementsSendByEmailDescription", resourceCulture);
            }
        }
        
        internal static string ConfirmationRaiseCreditLimitTitle {
            get {
                return ResourceManager.GetString("ConfirmationRaiseCreditLimitTitle", resourceCulture);
            }
        }
        
        internal static string ConfirmationRaiseCreditLimitOk {
            get {
                return ResourceManager.GetString("ConfirmationRaiseCreditLimitOk", resourceCulture);
            }
        }
        
        internal static string ConfirmationRaiseCreditLimitBack {
            get {
                return ResourceManager.GetString("ConfirmationRaiseCreditLimitBack", resourceCulture);
            }
        }
        
        internal static string FeedbackRaiseCreditLimitTitle {
            get {
                return ResourceManager.GetString("FeedbackRaiseCreditLimitTitle", resourceCulture);
            }
        }
        
        internal static string FeedbackRaiseCreditLimitDescription {
            get {
                return ResourceManager.GetString("FeedbackRaiseCreditLimitDescription", resourceCulture);
            }
        }
        
        internal static string ConfirmationOneLapRFTitle {
            get {
                return ResourceManager.GetString("ConfirmationOneLapRFTitle", resourceCulture);
            }
        }
        
        internal static string ConfirmationOneLapRFOk {
            get {
                return ResourceManager.GetString("ConfirmationOneLapRFOk", resourceCulture);
            }
        }
        
        internal static string ConfirmationOneLapRFBack {
            get {
                return ResourceManager.GetString("ConfirmationOneLapRFBack", resourceCulture);
            }
        }
        
        internal static string FeedbackOneLapRFSuccessTitle {
            get {
                return ResourceManager.GetString("FeedbackOneLapRFSuccessTitle", resourceCulture);
            }
        }
        
        internal static string FeedbackOneLapRFSuccessDescription {
            get {
                return ResourceManager.GetString("FeedbackOneLapRFSuccessDescription", resourceCulture);
            }
        }
        
        internal static string ConfirmationTwoLapRFTitle {
            get {
                return ResourceManager.GetString("ConfirmationTwoLapRFTitle", resourceCulture);
            }
        }
        
        internal static string ConfirmationTwoLapRFCheckTitle {
            get {
                return ResourceManager.GetString("ConfirmationTwoLapRFCheckTitle", resourceCulture);
            }
        }
        
        internal static string ConfirmationTwoLapRFOk {
            get {
                return ResourceManager.GetString("ConfirmationTwoLapRFOk", resourceCulture);
            }
        }
        
        internal static string ConfirmationTwoLapRFBack {
            get {
                return ResourceManager.GetString("ConfirmationTwoLapRFBack", resourceCulture);
            }
        }
        
        internal static string FeedbackTwoLapRFSuccessTitle {
            get {
                return ResourceManager.GetString("FeedbackTwoLapRFSuccessTitle", resourceCulture);
            }
        }
        
        internal static string FeedbackOTwoLapRFSuccessDescription {
            get {
                return ResourceManager.GetString("FeedbackOTwoLapRFSuccessDescription", resourceCulture);
            }
        }
        
        internal static string FeedbackRFErrorDescription {
            get {
                return ResourceManager.GetString("FeedbackRFErrorDescription", resourceCulture);
            }
        }
        
        internal static string ConfirmationRFAtribuitionTitle {
            get {
                return ResourceManager.GetString("ConfirmationRFAtribuitionTitle", resourceCulture);
            }
        }
        
        internal static string ConfirmationRFAtribuitionOk {
            get {
                return ResourceManager.GetString("ConfirmationRFAtribuitionOk", resourceCulture);
            }
        }
        
        internal static string ConfirmationRFAtribuitionBack {
            get {
                return ResourceManager.GetString("ConfirmationRFAtribuitionBack", resourceCulture);
            }
        }
        
        internal static string FeedbackRFSuccessAtribuitionTitle {
            get {
                return ResourceManager.GetString("FeedbackRFSuccessAtribuitionTitle", resourceCulture);
            }
        }
        
        internal static string FeedbackRFSuccessAtribuitionDescription {
            get {
                return ResourceManager.GetString("FeedbackRFSuccessAtribuitionDescription", resourceCulture);
            }
        }
        
        internal static string ConfirmationChangePaymentMethodTitle {
            get {
                return ResourceManager.GetString("ConfirmationChangePaymentMethodTitle", resourceCulture);
            }
        }
        
        internal static string ConfirmationChangePaymentMethodOk {
            get {
                return ResourceManager.GetString("ConfirmationChangePaymentMethodOk", resourceCulture);
            }
        }
        
        internal static string ConfirmationChangePaymentMethodBack {
            get {
                return ResourceManager.GetString("ConfirmationChangePaymentMethodBack", resourceCulture);
            }
        }
        
        internal static string ConfirmationChangePaymentMethodSuccessTitle {
            get {
                return ResourceManager.GetString("ConfirmationChangePaymentMethodSuccessTitle", resourceCulture);
            }
        }
        
        internal static string ConfirmationChangePaymentMethodSuccessDescription {
            get {
                return ResourceManager.GetString("ConfirmationChangePaymentMethodSuccessDescription", resourceCulture);
            }
        }
        
        internal static string ConfirmationChangePaymentMethodErrorTitle {
            get {
                return ResourceManager.GetString("ConfirmationChangePaymentMethodErrorTitle", resourceCulture);
            }
        }
        
        internal static string AllCasesConfirmationHomeSimulationOk {
            get {
                return ResourceManager.GetString("AllCasesConfirmationHomeSimulationOk", resourceCulture);
            }
        }
        
        internal static string AllCasesConfirmationHomeSimulationBack {
            get {
                return ResourceManager.GetString("AllCasesConfirmationHomeSimulationBack", resourceCulture);
            }
        }
        
        internal static string AllCasesFeedbackHomeSimulationBack {
            get {
                return ResourceManager.GetString("AllCasesFeedbackHomeSimulationBack", resourceCulture);
            }
        }
        
        internal static string Case1ConfirmationHomeSimulationTitle {
            get {
                return ResourceManager.GetString("Case1ConfirmationHomeSimulationTitle", resourceCulture);
            }
        }
        
        internal static string Case1FeedbackHomeSimulationTitle {
            get {
                return ResourceManager.GetString("Case1FeedbackHomeSimulationTitle", resourceCulture);
            }
        }
        
        internal static string Case1FeedbackHomeSimulationDescription {
            get {
                return ResourceManager.GetString("Case1FeedbackHomeSimulationDescription", resourceCulture);
            }
        }
        
        internal static string Case2ConfirmationHomeSimulationTitle {
            get {
                return ResourceManager.GetString("Case2ConfirmationHomeSimulationTitle", resourceCulture);
            }
        }
        
        internal static string Case2FeedbackHomeSimulationTitle {
            get {
                return ResourceManager.GetString("Case2FeedbackHomeSimulationTitle", resourceCulture);
            }
        }
        
        internal static string Case2FeedbackAprovedHomeSimulationDescription {
            get {
                return ResourceManager.GetString("Case2FeedbackAprovedHomeSimulationDescription", resourceCulture);
            }
        }
        
        internal static string Case2FeedbackErrorHomeSimulationDescription {
            get {
                return ResourceManager.GetString("Case2FeedbackErrorHomeSimulationDescription", resourceCulture);
            }
        }
        
        internal static string Case3ConfirmationHomeSimulationTitle {
            get {
                return ResourceManager.GetString("Case3ConfirmationHomeSimulationTitle", resourceCulture);
            }
        }
        
        internal static string Case3FeedbackHomeSimulationTitle {
            get {
                return ResourceManager.GetString("Case3FeedbackHomeSimulationTitle", resourceCulture);
            }
        }
        
        internal static string Case3FeedbackHomeSimulationDescription {
            get {
                return ResourceManager.GetString("Case3FeedbackHomeSimulationDescription", resourceCulture);
            }
        }
        
        internal static string Case4ConfirmationHomeSimulationTitle {
            get {
                return ResourceManager.GetString("Case4ConfirmationHomeSimulationTitle", resourceCulture);
            }
        }
        
        internal static string Case4FeedbackHomeSimulationTitle {
            get {
                return ResourceManager.GetString("Case4FeedbackHomeSimulationTitle", resourceCulture);
            }
        }
        
        internal static string Case4FeedbackHomeSimulationDescription {
            get {
                return ResourceManager.GetString("Case4FeedbackHomeSimulationDescription", resourceCulture);
            }
        }
        
        internal static string Case5ConfirmationHomeSimulationTitle {
            get {
                return ResourceManager.GetString("Case5ConfirmationHomeSimulationTitle", resourceCulture);
            }
        }
        
        internal static string Case5ConfirmationHomeSimulationDescription {
            get {
                return ResourceManager.GetString("Case5ConfirmationHomeSimulationDescription", resourceCulture);
            }
        }
        
        internal static string Case5FeedbackHomeSimulationTitle {
            get {
                return ResourceManager.GetString("Case5FeedbackHomeSimulationTitle", resourceCulture);
            }
        }
        
        internal static string Case5FeedbackHomeSimulationDescription {
            get {
                return ResourceManager.GetString("Case5FeedbackHomeSimulationDescription", resourceCulture);
            }
        }
        
        internal static string Case6ConfirmationHomeSimulationTitle {
            get {
                return ResourceManager.GetString("Case6ConfirmationHomeSimulationTitle", resourceCulture);
            }
        }
        
        internal static string Case6FeedbackHomeSimulationTitle {
            get {
                return ResourceManager.GetString("Case6FeedbackHomeSimulationTitle", resourceCulture);
            }
        }
        
        internal static string Case6FeedbackHomeSimulationDescription {
            get {
                return ResourceManager.GetString("Case6FeedbackHomeSimulationDescription", resourceCulture);
            }
        }
        
        internal static string LinkOneyContact {
            get {
                return ResourceManager.GetString("LinkOneyContact", resourceCulture);
            }
        }
    }
}
