// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ResxParser {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResx2 {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResx2() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ResxParser.SharedResx2", typeof(SharedResx2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string FirstLoginFluxIntro {
            get {
                return ResourceManager.GetString("FirstLoginFluxIntro", resourceCulture);
            }
        }
        
        internal static string FirstLoginFluxPhone {
            get {
                return ResourceManager.GetString("FirstLoginFluxPhone", resourceCulture);
            }
        }
        
        internal static string FirstLoginFluxEmail {
            get {
                return ResourceManager.GetString("FirstLoginFluxEmail", resourceCulture);
            }
        }
        
        internal static string FirstLoginFluxOneyPassword {
            get {
                return ResourceManager.GetString("FirstLoginFluxOneyPassword", resourceCulture);
            }
        }
        
        internal static string FirstLoginFluxPolicy {
            get {
                return ResourceManager.GetString("FirstLoginFluxPolicy", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string FindStore {
            get {
                return ResourceManager.GetString("FindStore", resourceCulture);
            }
        }
        
        internal static string FindStoreDetail {
            get {
                return ResourceManager.GetString("FindStoreDetail", resourceCulture);
            }
        }
        
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        internal static string IntegratedPosition {
            get {
                return ResourceManager.GetString("IntegratedPosition", resourceCulture);
            }
        }
        
        internal static string FinanceReserve {
            get {
                return ResourceManager.GetString("FinanceReserve", resourceCulture);
            }
        }
        
        internal static string CreditForm {
            get {
                return ResourceManager.GetString("CreditForm", resourceCulture);
            }
        }
        
        internal static string Consults {
            get {
                return ResourceManager.GetString("Consults", resourceCulture);
            }
        }
        
        internal static string ConsultsRender {
            get {
                return ResourceManager.GetString("ConsultsRender", resourceCulture);
            }
        }
        
        internal static string ConsultsExtracts {
            get {
                return ResourceManager.GetString("ConsultsExtracts", resourceCulture);
            }
        }
        
        internal static string ConsultsMovements {
            get {
                return ResourceManager.GetString("ConsultsMovements", resourceCulture);
            }
        }
        
        internal static string ConsultsReserveAccountMore {
            get {
                return ResourceManager.GetString("ConsultsReserveAccountMore", resourceCulture);
            }
        }
        
        internal static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        internal static string RequestRaiseCreditLimit {
            get {
                return ResourceManager.GetString("RequestRaiseCreditLimit", resourceCulture);
            }
        }
        
        internal static string RequestChangePaymentMethodAlert {
            get {
                return ResourceManager.GetString("RequestChangePaymentMethodAlert", resourceCulture);
            }
        }
        
        internal static string RequestChangePaymentMethod {
            get {
                return ResourceManager.GetString("RequestChangePaymentMethod", resourceCulture);
            }
        }
        
        internal static string RequestDigitalExtract {
            get {
                return ResourceManager.GetString("RequestDigitalExtract", resourceCulture);
            }
        }
        
        internal static string RequestExtractDuplicate {
            get {
                return ResourceManager.GetString("RequestExtractDuplicate", resourceCulture);
            }
        }
        
        internal static string RequestReplaceCard {
            get {
                return ResourceManager.GetString("RequestReplaceCard", resourceCulture);
            }
        }
        
        internal static string Insurances {
            get {
                return ResourceManager.GetString("Insurances", resourceCulture);
            }
        }
        
        internal static string FeedbackPopup {
            get {
                return ResourceManager.GetString("FeedbackPopup", resourceCulture);
            }
        }
        
        internal static string ConfirmationPopup {
            get {
                return ResourceManager.GetString("ConfirmationPopup", resourceCulture);
            }
        }
        
        internal static string EmailConfirmationFlux {
            get {
                return ResourceManager.GetString("EmailConfirmationFlux", resourceCulture);
            }
        }
        
        internal static string PhoneConfirmationFlux {
            get {
                return ResourceManager.GetString("PhoneConfirmationFlux", resourceCulture);
            }
        }
    }
}
